fastcash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kemusic.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kemusic/urls.py
from django.urls import path
from .import views


app_name = 'kemusic'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.signin, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('', views.index, name='index'),
    path('?P<album_id>[0-9]/', views.detail, name='detail'),
    path('new-album', views.create_album, name='create_album'),
    path('<int:pk>/update-album', views.AlbumUpdateView.as_view(), name='album-update'),
    path('(?P<album_id>[0-9]+)/delete-album', views.album_delete, name='album-delete'),
    path('(?P<album_id>[0-9]+)/new-song', views.create_song, name='create-song'),
    path('<int:pk>/update-song', views.SongUpdateView.as_view(), name='song-update'),
    path('(?P<album_id>[0-9]+)/delete-song/(?P<song_id>[0-9]+)', views.delete_song, name='song-delete'),
]

kemusic/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
# Create your models here.
class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    album_name = models.CharField(max_length=25)
    artist_name = models.CharField(max_length=30)
    album_genre = models.CharField(max_length=10)
    album_cover = models.FileField()

    def get_absolute_url(self):
        return reverse('kemusic:index')


class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    song_name = models.CharField(max_length=25)
    song_audio = models.FileField()

def get_absolute_url(self):
    return reverse('kemusic:detail', args=[str(self.pk)])

kemusic/forms.py
from django import forms
from .models import Album
from .models import Song
from django.contrib.auth.models import User



class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['album_name', 'artist_name', 'album_genre', 'album_cover']

class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_name', 'song_audio']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

kemusic/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Album, Song
from .forms import AlbumForm, SongForm, UserForm
from django.views.generic import UpdateView
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q


# Create your views here.
@login_required(login_url='kemusic:login')
def index(request):
    albums = Album.objects.filter(user=request.user)
    song_results = Song.objects.all()
    query = request.GET.get("q")
    if query:
        albums = albums.filter(
            Q(album_name__icontains=query) |
            Q(artist_name__icontains=query)

        ).distinct()
        song_results = song_results.filter(
            Q(song_name__icontains=query)
        ).distinct()
        return render(request, 'kemusic/index.html', {
            'albums':  albums,
            'songs': song_results
         })
    return render(request, 'kemusic/index.html', {'albums': albums})
def detail(request,album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'kemusic/detail.html', {'album': album})


def create_album(request):
    form = AlbumForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        albums = Album.objects.filter(user=request.user)
        for album in albums:
            if album.album_name == form.cleaned_data.get('album_name'):
                context = {
                    'form': form,
                    'message': 'This album is already added',
                }
                return render(request, 'kemusic/create_album.html', context)
        album = form.save(commit=False)
        album.album_cover = request.FILES['album_cover']
        album.user = request.user
        album.save()
        return render(request, 'kemusic/detail.html', {'album': album})
    return render(request, 'kemusic/create_album.html', {'form': form})

class AlbumUpdateView(UpdateView):
    model = Album
    fields = ['album_name', 'artist_name', 'album_cover', 'album_genre']
    template_name = "kemusic/create_album.html"

def album_delete(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect('/')

def create_song(request, album_id):
    form =SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        for s in album.song_set.all():
            if s.song_name == form.cleaned_data.get('song_name'):
                context = {
                    'form': form,
                    'message':'You already added that song',
                }
            return render(request, 'kemusic/create_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.song_audio = request.FILES['song_audio']
        song.save()
        context = {
            'album': album,
            'message': 'Song Created Successfully',
        }
        return render(request, 'kemusic/detail.html', context)
    return render(request, 'kemusic/create_song.html', {'form':form})

class SongUpdateView(UpdateView):
    model = Song
    fields =['song_name', 'song_audio']
    template_name = 'kemusic/create_song.html'


def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = get_object_or_404(Song, pk=song_id)
    song.delete()
    context = {
        'album':album,
        'message': 'Song Deleted Successfully!'
    }
    return render(request, 'kemusic/detail.html', context)

def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('kemusic:index')
    return render(request, 'registration/signup.html', {'form': form})

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        #if user.is_active:
        login(request, user)
        return redirect('kemusic:index')
        #return render(request, 'registration/login.html')
    return render(request, 'registration/login.html')


def logout_user(request):
    logout(request)
    context = {
        'message': 'logged Out!'
    }
    return redirect( 'kemusic:login')

kemusic/templates/kemusic/base.html
<html lan="en">
<head>
  <title>{% block title %}{% endblock %}</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">





</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'kemusic:index' %}">+254 Music</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'kemusic:index' %}">Home <span class="sr-only">(current)</span></a></li>         <li><a href="#"><i class="fas fa-headphones"></i> Albums</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'kemusic:create_album' %}"><i class="fas fa-plus-square"></i> Add Album</a></li>
        <li><a href="{% url 'kemusic:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}
</body>
</html>

kemusic/templates/kemusic/create_album.html
{% extends 'kemusic/base.html' %}
{% block title %}Create Album{% endblock %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="col-sm-4"></div>
    <div class="col-sm-3">
        <div class="panel panel-default panel-body">
            <h3 class="text-info text-center text-capitalize">{% if object %}Update&nbsp;<i class="fas fa-headphones-alt fn-3x"></i>&nbsp; Album{% else %}new<i class="fas fa-headphones-alt fn-3x"></i>&nbsp;album{% endif %}</h3>
            <hr>

            <form method="post" enctype="multipart/form-data">
                {% if message %}
                <div class="alert alert-danger">
                    <h4>{{ message }}</h4>
                </div>
                {% endif %}
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg active">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

kemusic/templates/kemusic/create_song.html
{% extends 'kemusic/base.html' %}
{% load crispy_forms_tags %}
{% block title %}New Song{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <h3 class="text-primary text-capitalize">{% if object %}Update&nbsp;<i class="fas fa-headphones-alt fn-3x"></i>&nbsp; Song{% else %}new<i class="fas fa-headphones-alt fn-3x"></i>&nbsp;song{% endif %}</h3>
                    {% if message %}
                    <div class="alert alert-danger">
                        <h4>{{ message }}<h4>
                    </div>
                    {% endif %}
                    <hr>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btm btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

kemusic/templates/kemusic/detail.html
{% extends 'kemusic/base.html' %}
{% block title %}Detail{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">

        <!--Album Information-->
        <div class="col-sm-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{ album.album_cover.url }}" class="img img-responsive" alt="" style="height: 200px; width:80%;">
                <div class="caption">
                <h5>{{ album.album_name }}</h5>
                 <h5>{{ album.album_genre }}</h5>
            </div>
         </div>
        </div>
    </div>

    <!--song information-->
    <div class="col-sm-9">
    <ul class="nav nav-pills">
        <li class="active"><a href="">Songs</a></li>
        <li><a href="{% url 'kemusic:create-song' album.id %}">Add song</a></li>
    </ul>
    <div class="panel panel-default" style="margin: 3px;">
        <div class="panel-body">
            <h5 class="text-info">Song</h5>
            <hr>

            <table class="table">
                <thead>
                <th>Song Name</th>
                <th>Audio</th>
                <th>Favourite</th>
                <th>Action</th>
                </thead>
                <tbody>
                {% if album.song_set %}
                    {% for song in album.song_set.all %}
                    <tr>
                        <td>{{ song.song_name }}</td>
                        <td><a href="{{ song.song_audio.url }}" class="btn btn-danger btn-sm" target="_blank"><i class="fas fa-play"></i></a></td>
                        <td><a href="" class="btn btn-danger btn-sm"><i class="fas fa-star"></i></td></a>
                        <td>
                            <a href="{% url 'kemusic:song-update' album.id %}" class="btn btn-success btn -sm"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'kemusic:song-delete' album.id song.id %}" class="btn btn-danger btn -sm"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>

    </div>
    </div>

</div>
</div>
{% endblock %}

kemusic/templates/kemusic/index.html
{% extends 'kemusic/base.html' %}
{% block title %}Albums{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-3">
                <div class="thumbnail" style="background-color: lightskyblue;">
                    <a href="{% url 'kemusic:detail' album.id %}">
                    <img src="{{ album.album_cover.url }}" class="img img-responsive img-circle" alt="" style="height: 250px;">
                    </a>
                    <div class="caption">
                        <h4 style="..">{{ album.album_genre }}</h4>
                        <h4 style="..">{{ album.album_name }}</h4>
                        <h5 style="..">{{ album.artist_name }}</h5>
                        <a href="{% url 'kemusic:album-update' album.id %}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'kemusic:album-delete' album.id %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                        <a href="" class="btn btn-success" style="float:right"><i class="fas fa-heart"></i></a>
                    </div>
                </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}